%%% DynaEst 3.032 10/22/2000
% Copyright (c) 2000 Yaakov Bar-Shalom
%
% CommonWindow , Window for user to select

h_CommonWindow = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
   'NumberTitle','off', ...
   'PointerShapeCData',mat1, ... 
   'Position',[scrsz(3)/9.5 scrsz(4)/9.5 scrsz(3)/1.9 scrsz(4)/1.9], ...
   'resize','off',...
   'Tag','Fig2');

set(h_CommonWindow,'CloseRequestFcn','CloseCommonWindow')
cwsz = [scrsz(3)/9.5 scrsz(4)/9.5 scrsz(3)/1.9 scrsz(4)/1.9] ;


h_Next = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[7.9/10*cwsz(3) 8/10*cwsz(4) cwsz(3)/6 cwsz(4)/13], ...
   'String','Next >>', ...
   'callback','NextProcess;',...
	'Tag','Pushbutton1');
h_Prev = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'ListboxTop',0, ...
    'Position',[7.9/10*cwsz(3) 7/10*cwsz(4) cwsz(3)/6 cwsz(4)/13], ...
   'String','<< Prev', ...
   'CallBack','PrevProcess;',...
	'Tag','Pushbutton2');
% $$$ h_Reset = uicontrol('Parent',h_CommonWindow, ...
% $$$ 	'Units','points', ...
% $$$ 	'ListboxTop',0, ...
% $$$ 	'Position',[333 187.5 69 22.5], ...
% $$$    'String','Reset', ...
% $$$    'enable','off',...
% $$$ 	'Tag','Pushbutton3');
% $$$ h_AutoPlay = uicontrol('Parent',h_CommonWindow, ...
% $$$ 	'Units','points', ...
% $$$ 	'ListboxTop',0, ...
% $$$ 	'Position',[333 148.5 69 22.5], ...
% $$$    'String','Auto Play', ...
% $$$    'enable','off',...
% $$$ 	'Tag','Pushbutton4');
% $$$ h_Info = uicontrol('Parent',h_CommonWindow, ...
% $$$ 	'Units','points', ...
% $$$ 	'ListboxTop',0, ...
% $$$ 	'Position',[333 64.5 69 22.5], ...
% $$$    'String','Info', ...
% $$$    'callback','AboutDialog;',...
% $$$ 	'Tag','Pushbutton5');
h_Close = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'Callback','figure(h_CommonWindow); CloseCommonWindow;', ...
	'ListboxTop',0, ...
    'Position',[7.8/10*cwsz(3) 1/15*cwsz(4) cwsz(3)/6 cwsz(4)/13], ...
	'String','Close', ...
	'Tag','Pushbutton6');
%	'Position',[333 23.25 69 22.5], ...
FrameBackColor = [0.8 0.8 0.8];
uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',FrameBackColor, ...
	'ListboxTop',0, ...
    'Position',[1/12*cwsz(3) 1/2*cwsz(4) 23/36*cwsz(3) 3/7*cwsz(4)], ...
	'Style','frame', ...
	'Tag','Frame1');

%	'Position',[33.75 157.5 273 137.25], ...
fwsz = [1/12*cwsz(3) 1/2*cwsz(4) 23/36*cwsz(3) 3/7*cwsz(4)] ;

h_About = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Max',100, ...
    'Position',[1/12*cwsz(3) 1/15*cwsz(4) 23/36*cwsz(3) 2.7/7*cwsz(4)], ...
	'Style','edit', ...
	'Tag','EditText1');
%	'Position',[33 22.5 277.5 114.75], ...

if isempty(Project_Filename)
   set(h_CommonWindow,'name','Project:Untitled*');
else
   set(h_CommonWindow,'name',['Project:', Project_Filename]);
end

