%%% DynaEst 3.032 12/28/2000
% Copyright (c) 2000 Yaakov Bar-Shalom
%
% DataResource , Select where Data is come from

StateFlag = 1 ;
% scrsz =     1     1   800   600
%cwsz = [scrsz(3)/9.5 scrsz(4)/9.5 scrsz(3)/1.9 scrsz(4)/1.9] ;
%cwsz =   84.2105   63.1579  421.0526  315.7895 ;
%fwsz = [1/12*cwsz(3) 1/2*cwsz(4) 23/36*cwsz(3) 3/7*cwsz(4)] ;
%fwsz =   [35.0877  157.8947  269.0058  135.3383];

%   'Position',[1/12*cwsz(3) 1/2*cwsz(4) 23/36*cwsz(3) 3/7*cwsz(4)], ...
h_HeadTitle = uicontrol('Parent',h_CommonWindow, ...
      'Units','points', ...
      'HorizontalAlignment','left', ...
      'ListboxTop',0, ...
    	'Position',[1.1/12*cwsz(3) 9.3/10*cwsz(4) cwsz(3)/2 10], ...
      'BackgroundColor',FrameBackColor, ...
      'Style','text', ...
      'String','Data resource:',...  
      'FontWeight', 'bold', ...
      'Tag','StaticText2');

%        'Position',[34 295 200 10], ...
h_RadioButton1 = uicontrol('Parent',h_CommonWindow, ...
   'Units','points', ...
   'Callback',['set(h_RadioButton1,''Value'',1);',...
      'set(h_RadioButton2,''Value'',0);',...
      'set(h_RadioButton3,''Value'',0);',...
      'set(h_RadioButton4,''Value'',0);',...
      'SimulationFlag = 1;',...
      'DataResourceFlag = DATA_SIMULATION;',...
       'StepNumber = 11;'],...
   'ListboxTop',0, ...   
   'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+ fwsz(4)*7/10 fwsz(3)*8/10 15], ...
  	'BackgroundColor',FrameBackColor, ...
	'String','Define interactively', ...
   'Style','radiobutton', ...
   'Value',0,...
	'Tag','Radiobutton1');

%	'Position',[64.5 251.5 200 21], ...

h_RadioButton2 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
   'Callback',['set(h_RadioButton1,''Value'',0);',...
      'set(h_RadioButton2,''Value'',1);',...
      'set(h_RadioButton3,''Value'',0);',...
      'set(h_RadioButton4,''Value'',0);',...
      'SimulationFlag = 2;',...
      'DataResourceFlag = DATA_SIMULATION;',...
      'StepNumber = 11;'],...
   'ListboxTop',0, ...
  	'BackgroundColor',FrameBackColor, ...
    'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+ fwsz(4)*(7/10-1/7) fwsz(3)*8/10 15], ...
	'String','Import system state from an external file', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton2', ...
	'Value',0);

%	'Position',[64.5 231 200 21], ...
h_RadioButton3 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
   'Callback',['set(h_RadioButton1,''Value'',0);',...
      'set(h_RadioButton2,''Value'',0);',...
      'set(h_RadioButton3,''Value'',1);',...
      'set(h_RadioButton4,''Value'',0);',...
      'SimulationFlag = 3;',...
      'DataResourceFlag = DATA_SIMULATION;',...
      'StepNumber = 11;'],...
   'ListboxTop',0, ...
  	'BackgroundColor',FrameBackColor, ...
    'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+ fwsz(4)*(7/10-2/7) fwsz(3)*8/10 15], ...    
   'String','Import ground truth from an external file', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton3', ...
	'Value',0);
%	'Position',[64.5 210.5 200 21], ...

h_RadioButton4 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
   'callback',['set(h_RadioButton1,''Value'',0);',...
      'set(h_RadioButton2,''Value'',0);',...
      'set(h_RadioButton3,''Value'',0);',...
      'set(h_RadioButton4,''Value'',1);',...
      'SimulationFlag = 4;',...
      'DataResourceFlag = DATA_MEASUREMENT;',...
      'StepNumber = 11;'],...
   'ListboxTop',0, ...
   'BackgroundColor',FrameBackColor, ...
   'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+ fwsz(4)*(7/10-3/7) fwsz(3)*8/10 15], ...       
	'String','Import measuremnet from an external file', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton4');
%	'Position',[64.5 190 200 21], ...
switch SimulationFlag
case 1
%   MeasurementType = 0 ;
   DataResourceFlag == DATA_SIMULATION;
   set(h_RadioButton1,'value',1);
   StepNumber = 11;
case 2
   %MeasurementType = 0 ;
   DataResourceFlag == DATA_SIMULATION;
   set(h_RadioButton2,'value',1);
   StepNumber = 11;
case 3
   %MeasurementType = 0 ;
   DataResourceFlag == DATA_SIMULATION;
   set(h_RadioButton3,'value',1);
   StepNumber = 11;
case 4
   %MeasurementType = 1 ;
   DataResourceFlag ==DATA_MEASUREMENT;
   set(h_RadioButton4,'value',1);
   StepNumber = 11;
end

help_string=['In this window, you can select the data input source',...
      ' If you want to define interactively the true target trajectory, select, ''Define interactively''.',...
      ' if you want to import truth from an external file, select, ''Import ground truth''.',...
      ' if you want to import system state from an external file, select, ''Import system state''.',... 
      ' Or, if you want to import measurements from an external data file,',...
       ' for example, from a real sensor or another simulation program, select, ''Import measurement file''.' ,...
char(10), char(10),    'Press ''Next >>'' when done to go to the next step. Press ''<< Prev'' to go back to the previous step.',...
   ' Press ''Close'' to abort the project definition.'];
 


set(h_About,'String',help_string, 'enable', 'inactive');

set(h_Prev,'enable','off');
