%%% DynaEst 3.032 10/22/2000
% Copyright (c) 2000 Yaakov Bar-Shalom
%
% DesignTracker, Design Tracker

if ( exist('h_CommonWindow') == 0 ) return; end

if (ishandle(h_CommonWindow) == 0)
   CommonWindow;
end

if new_title<=0
	set(h_HeadTitle, 'String','Source for tracker design:');
else
	h_HeadTitle = uicontrol('Parent',h_CommonWindow, ...
      'Units','points', ...
      'HorizontalAlignment','left', ...
      'ListboxTop',0, ...
      'Position',[1.1/12*cwsz(3) 9.3/10*cwsz(4) cwsz(3)/2 10], ...
      'BackgroundColor',FrameBackColor, ...
      'Style','text', ...
      'String','Source for tracker design:',... 
	'FontWeight', 'bold', ... 
      'Tag','StaticText2');
end

h_RadioButton1 = uicontrol('Parent',h_CommonWindow, ...
   'Units','points', ...
   'Callback',['set(h_RadioButton1,''Value'',1);',...
      'set(h_RadioButton2,''Value'',0);',...
      'NewFlag = 1; TrackerSetupFlag = 1; StepNumber = 511;'],...
   'ListboxTop',0, ...
   'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+ fwsz(4)*6.5/10 fwsz(3)*8/10 15], ...
   'BackgroundColor',FrameBackColor, ...
	'String','Interactive setup', ...
   'Style','radiobutton', ...
   'Value',1,...
	'Tag','Radiobutton1');

h_RadioButton2 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
   'Callback',['set(h_RadioButton1,''Value'',0);',...
      'set(h_RadioButton2,''Value'',1);',...
      'NewFlag = 1; TrackerSetupFlag = 2; StepNumber = 512;'],...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+ fwsz(4)*(6.5/10-1/4) fwsz(3)*8/10 15], ...
    'String','Import tracker from an external file', ...
   'BackgroundColor',FrameBackColor, ...
	'Style','radiobutton', ...
	'Tag','Radiobutton2', ...
	'Value',0);


help_string=['In this window, you can select the source from which the tracker design is obtained.', char(10), char(10), 'If you want to specify the tracker interactively within Dynaest, select ''Interactive setup''. Or, if you want to import the tracker design from an external data file, for example, from another program, select ''External file''.', char(10), char(10), 'Press ''Next >>'' when done to go to the next step. Press ''<< Prev'' to go back to the previous step. Press ''Close'' to abort the project definition.'];

set(h_About,'String',help_string, 'enable', 'inactive');

if TrackerSetupFlag == 1
   set(h_RadioButton1,'Value',1);
   set(h_RadioButton2,'Value',0);
   StepNumber = 511;
elseif TrackerSetupFlag == 2
   set(h_RadioButton1,'Value',0);
   set(h_RadioButton2,'Value',1);
   StepNumber = 512; 
end


   

   
