%%% DynaEst 3.032 10/22/2000
% Copyright (c) 2000 Yaakov Bar-Shalom
%
%KFParameter 

% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load KFParameter

h0 = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'Name','Set Kalman Filter Parameters', ...
	'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
	'Position',[185 110 436.5 310.5], ...
	'Resize','off', ...
	'Tag','Fig2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','SetKFFromFile; Close(''Set Kalman Filter Parameters''); MonteCarlo; ', ...
	'ListboxTop',0, ...
	'Position',[342 255 59 22.5], ...
	'String','Next >>', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','Close(''Set Kalman Filter Parameters''); FilterAlgorithm; ', ...
	'ListboxTop',0, ...
	'Position',[342 214.5 59 22.5], ...
	'String','<< Prev', ...
	'Tag','Pushbutton2');
% $$$ h1 = uicontrol('Parent',h0, ...
% $$$ 	'Units','points', ...
% $$$ 	'ListboxTop',0, ...
% $$$ 	'Position',[342 174 59 22.5], ...
% $$$ 	'String','Reset', ...
% $$$ 	'Tag','Pushbutton3');
% $$$ h1 = uicontrol('Parent',h0, ...
% $$$ 	'Units','points', ...
% $$$ 	'ListboxTop',0, ...
% $$$ 	'Position',[342 133.5 59 22.5], ...
% $$$ 	'String','Auto Play', ...
% $$$ 	'Tag','Pushbutton4');
% $$$ h1 = uicontrol('Parent',h0, ...
% $$$ 	'Units','points', ...
% $$$ 	'ListboxTop',0, ...
% $$$ 	'Position',[342 60.75 59 22.5], ...
% $$$ 	'String','Info', ...
% $$$ 	'Tag','Pushbutton5');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[342 20.25 59 22.5], ...
	'String','Close', ...
	'Tag','Pushbutton6');
h_Edit = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[24 20.25 298.5 93.75], ...
	'String','About Kalman Filter Parameters ', ...
   'Style','edit', ...
   'Max',100,...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[22.3448275862069 142.137931034483 299.172413793103 145.862068965517], ...
	'Style','frame', ...
	'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[36 252 191.25 27], ...
	'String','Set up System Matrices and Noise Statistics', ...
	'Style','text', ...
	'Tag','StaticText1');
h_RadioButton1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[72 233.25 95.25 13.5], ...
   'String','Set Up Step by Step.', ...
   'CallBack', 'set(h_RadioButton2,''value'',0); set(h_RadioButton1,''Value'',1); ',...
	'Style','radiobutton', ...
	'Tag','Radiobutton1');
h_RadioButton2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[72 208.5 89.25 14.25], ...
   'String','Load File to Set up', ...
   'CallBack', 'set(h_RadioButton2,''value'',1); set(h_RadioButton1,''Value'',0); ',...
	'Style','radiobutton', ...
	'Tag','Radiobutton2', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[89.25 187.5 38.25 13.5], ...
	'String','Filename:', ...
	'Style','text', ...
	'Tag','StaticText2');
h_filename = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[142.5 184.5 75 17.25], ...
	'String','kfinp.m', ...
	'Style','edit', ...
	'Tag','EditText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[255 184.5 38.25 16.5], ...
   'String','Browse', ...
   'CallBack',[...
      '[filename pathname] = uigetfile(''*.*'',''Choose a Parameter File for Kalman Filter'');',...
      'set(h_filename,''String'',filename);'],...
	'Tag','Pushbutton9');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[171 153 52.5 18.75], ...
   'String','View', ...
   'CallBack',['mode=1; nmf=1; ', ...
              'show('' '',''clear''), SetKFFromFile; chkfghif, chkqrvwf, chkx0p0;'],...
	'Tag','Pushbutton8', ...
	'Value',1);
