%%% DynaEst 3.032 10/22/2000
% Copyright (c) 2000 Yaakov Bar-Shalom
%
% Mainwindow

load Start % color map of h_MainWindow and h_CommonWindow 
scrsz=get(0,'ScreenSize') ;

h_MainWindow = figure('Units','points', ...
	'Color',[0 0 0], ...
	'Colormap',mat0, ...
	'Name','DynaEst 3.3', ...
   'NumberTitle','off', ...
   'MenuBar','none',...
   'PointerShapeCData',mat1, ...
	'Position',[ scrsz(3)/10 scrsz(4)/10 scrsz(3)/1.7 scrsz(4)/1.7], ...
   'Tag','Fig1');

set(h_MainWindow,'CloseRequestFcn','CloseDynaest')

%   'CloseRequestFcn','CloseDynaest;',...
h_File = uimenu('Parent',h_MainWindow, ...
	'Label','&File', ...
	'Tag','uimenu1');
file_new_menu=uimenu('Parent',h_File, ...
   'Label','&New', ...
   'CallBack','NewProject',...
   'Tag','Subuimenu1');
file_open_menu=uimenu('Parent',h_File, ...
   'Label','&Open',...
   'CallBack','OpenProject;',...
   'Tag','Subuimenu2');
file_close_menu=uimenu('Parent',h_File, ...
   'Label','&Close',...
   'CallBack','CloseProject',...
   'Tag','Subuimenu3');
file_save_menu=uimenu('Parent',h_File, ...
   'Label','&Save',...
   'Separator','on',...
   'CallBack','SaveProject;',...
   'Tag','Subuimenu4');
file_saveas_menu = uimenu('Parent',h_File, ...
   'Label','Save &As',...
   'CallBack','Project_Filename = []; SaveProject;',...
   'Tag','Subuimenu5');
file_pagesetup_menu=uimenu('Parent',h_File, ...
   'Label','Pa&ge Setup...',...
   'Separator','on',...
   'CallBack','pagedlg;',...
   'Tag','Subuimenu6');
file_print_menu = uimenu('Parent',h_File, ...
   'Label','&Print...',...
   'CallBack','printdlg',...
   'Tag','Subuimenu7');
file_exit_menu = uimenu('Parent',h_File, ...
   'Label','E&xit', ...
   'Separator','on',...
   'CallBack','CloseDynaest;',...
   'Tag','Subuimenu8');

setup_menu = uimenu(h_MainWindow,'label','&Setup');
set_system_menu=uimenu(setup_menu,'label','Data &Resource',...
   'CallBack','SetupNumber = 1; SetupProcess;','Enable','off');
set_export_menu=uimenu(setup_menu,'label','&Preaction && Filtering',...
   'callBack','SetupNumber = 2; SetupProcess;','Enable','off');
set_monte_menu = uimenu(setup_menu,'label','Monte &Carlo Run',...
   'callback','SetupNumber = 3; SetupProcess;','Enable','off');

view_menu=uimenu(h_MainWindow, 'label', '&View');
view_result_menu = uimenu(view_menu, 'label', 'Show &Results', ...
   'callback','SetupNumber = 4; SetupProcess;',...
   'enable','off',...
   'Interruptible', 'on' );
view_legend_menu=uimenu(view_menu, 'label', '&Legend', ...
   'Interruptible', 'on', ...
   'enable','off','checked','on',...
   'CallBack',[...
      'if (strcmp( get(view_legend_menu,''checked''),''on'')) ',...
      		'set(view_legend_menu,''checked'',''off''); legend off;',...
      'else ',...
           'set(view_legend_menu,''checked'',''on''); Redraw;',...
      'end']);
view_grid_menu=uimenu(view_menu, 'label', '&Grids', ...
   'Interruptible', 'on', 'checked','off','separator', 'on',...   
   'enable','off',...
   'CallBack',[...
      'if (strcmp( get(view_grid_menu,''checked''),''on'')) ',...
      ' grid off;',...            
      ' set(view_grid_menu,''check'',''off''); ',...
      'else ',...
      	' grid on;',...
      	' set(view_grid_menu,''check'',''on''); ',...
      'end']);
view_zoomin_menu = uimenu(view_menu, 'label', 'Zoom &In', ...
   'Interruptible', 'on', 'separator', 'on',...
   'enable','off',...
   'callback',[...
      'legend off;',...
      'set(view_legend_menu,''check'',''off'');',...   
      'zoom on; ']);
view_zoomout_menu = uimenu(view_menu, 'label', 'Zoom &Out', ...
   'Interruptible', 'on', 'enable', 'off',...
   'callback',[...
      'legend off;',...
      'zoom out; ']);
view_redraw_menu =uimenu(view_menu,'label','&Redraw',...
   'callback','redraw;',...
   'enable','off');
view_clear_menu =uimenu(view_menu,'label',...
   '&Clear Current Plot','callback','ClearScreen;');
% next trajectory
h_NextTrajectory = uimenu(view_menu,'label',...
   '&Next Trajectory','callback','NextTrajectory;',...
   'separator','on','enable','off');
h_PrevTrajectory =uimenu(view_menu,'label',...
   '&Previous Trajectory','callback','PrevTrajectory;','enable','off');


simulation_menu = uimenu('Parent',h_MainWindow, ...
	'Label','S&imulation', ...
	'Tag','uimenu2');
simu_montecarlo_menu = uimenu('Parent',simulation_menu, ...
   'Label','&Do Monte Carlo Runs', ...
   'callback','SetupNumber = 5; SetupProcess;',...
   'enable','off',...
   'Tag','Subuimenu21');

help_menu=uimenu(h_MainWindow, 'label', '&Help');
help_about_menu=uimenu(help_menu, 'label', '&About', ...
   'Interruptible', 'on', 'enable', 'on',...
   'callback','AboutDialog;');

DisableProjectMenu;