%%% DynaEst 3.032 10/22/2000
% Copyright (c) 2000 Yaakov Bar-Shalom
%
% MatrixWindow, show common Matrix window for Matrix display and input

StateFlag = StateFlag + 1  ;
h_NameOfMatrix = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
   'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+fwsz(4)*8/10 fwsz(3)*0.5 15], ...
   'BackgroundColor',FrameBackColor, ...
	'Style','text', ...
   'Tag','StaticText1');
h_ValueOfMatrix = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'Max',10, ...
    'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+fwsz(4)*1/10 fwsz(3)*4/5 fwsz(4)*3.5/5], ...
    'Style','edit', ...
	'Tag','EditText2');

