%%% DynaEst 3.032 10/22/2000
% Copyright (c) 2000 Yaakov Bar-Shalom
%
% PopupMenu1, Show Title and Popupmenu on the Common Window

if (exist('h_HeadTitle1') == 1)
   if ishandle(h_HeadTitle1)
      delete(h_HeadTitle1);
   end
end

%%% For what ????? - will be deleted if no error found
%clear itx jtx itxjtxvar itxcmd ;
   % for itx1=1:4
      %for jtx1=1:4
        %itxjtxvar=['h_Text', num2str(itx1), num2str(jtx1)];
          %itxcmd= ['if (exist(''', itxjtxvar, ''') == 1),  if ishandle(', itxjtxvar, '), delete(', itxjtxvar, ');  end; end;'];
         % eval(itxcmd)
           % itxjtxvar=['h_Edit', num2str(itx1), num2str(jtx1)];
          %itxcmd= ['if (exist(''', itxjtxvar, ''') == 1),  if ishandle(', itxjtxvar, '), delete(', itxjtxvar, ');  end; end;'];
%          eval(itxcmd)
   %     end
%    end

new_title=1;
if (exist('h_HeadTitle') == 0)

else
  if ishandle(h_HeadTitle)
	new_title=0;
  end
end

if new_title<=0
	set(h_HeadTitle, 'String','IMM estimator parameters:');
else
	h_HeadTitle = uicontrol('Parent',h_CommonWindow, ...
      'Units','points', ...
      'HorizontalAlignment','left', ...
      'ListboxTop',0, ...
      'Position',[1.1/12*cwsz(3) 9.3/10*cwsz(4) cwsz(3)/2 10], ...
  	   'BackgroundColor',FrameBackColor, ...
      'Style','text', ...
      'String','IMM estimator parameters:',... 
	'FontWeight', 'bold', ... 
      'Tag','StaticText2');
end

h_HeadTitle1 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
   'HorizontalAlignment','left', ...
	'BackgroundColor',FrameBackColor, ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+ fwsz(4)*0.8 fwsz(3)*0.3 10], ...
	'String','IMM module to design:', ...
	'Style','text', ...
	'Tag','StaticText1');

str = zeros(nmf,8);
for i = 1:nmf
   str(i,1:6) = 'Model ';
   str2=sprintf('%2d',i);
   str(i,7:8) = str2;
end

h_Popupmenu1 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'ListboxTop',0, ...    
    'Position',[fwsz(1)+fwsz(3)*0.4 fwsz(2)+ fwsz(4)*0.5 fwsz(3)*0.3 15], ...
    'BackgroundColor','white', ...
	'string',char(str),...
	'Style','popupmenu', ...
	'Tag','PopupMenu1', ...
   'Value',1);

set(h_Popupmenu1,'value',mode);

help_string=['In this window, you can select IMM estimator for which you want set the design parameters.', char(10), char(10), 'Select the estimator from the drop-down list.', char(10), char(10), 'Press ''Next >>'' when done to go to the next step. Press ''Close'' to abort the tracker definition.'];

set(h_About,'String',help_string, 'enable', 'inactive');
