%%% DynaEst 3.032 11/29/2000
% Copyright (c) 2000 Yaakov Bar-Shalom
%
% ExprotTracker, Export Tracker & MonterCalro Run

set(set_monte_menu,'Enable','on');
StateFlag == 4 ;

new_title=1;
if ~exist('h_HeadTitle')
  if ishandle(h_HeadTitle)
	new_title=0;
  end
end

if new_title ==0
   set(h_HeadTitle, 'String','Select Monte Carlo:');
  else
	h_HeadTitle = uicontrol('Parent',h_CommonWindow, ...
      'Units','points', ...
      'HorizontalAlignment','left', ...
      'ListboxTop',0, ...
      'Position',[1.1/12*cwsz(3) 9.3/10*cwsz(4) cwsz(3)/2 10], ...
      'BackgroundColor',FrameBackColor, ...
      'Style','text', ...
      'String','Define filter model:',...  
	'FontWeight', 'bold', ...
   'Tag','StaticText2');
end

h_RadioButton1 = uicontrol('Parent',h_CommonWindow, ...
   'Units','points', ...
   'Callback',['set(h_RadioButton1,''Value'',1);',...
      'set(h_RadioButton2,''Value'',0);',...
      'MonteSetupFlag = 1;',...
      'if FilterAlgorithmFlag == ALGORITHM_IMM StepNumber = 790 ; else StepNumber = 690 ;end' ],...
   'ListboxTop',0, ...
   'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+ fwsz(4)*6.5/10 fwsz(3)*8/10 15], ...
   'String','Monte carlo run', ...
   'BackgroundColor',FrameBackColor, ...
   'Style','radiobutton', ...
   'Value',0,...
	'Tag','Radiobutton1');

h_RadioButton2 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
   'Callback',['set(h_RadioButton1,''Value'',0);',...
      'set(h_RadioButton2,''Value'',1);',...
      'MonteSetupFlag = 2;',...
      'if FilterAlgorithmFlag == ALGORITHM_IMM StepNumber = 792 ; else StepNumber = 692 ;end' ],...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+ fwsz(4)*(6.5/10-1/4) fwsz(3)*8/10 15], ...
	'String','Export tracker to an external file', ...
   'BackgroundColor',FrameBackColor, ...
	'Style','radiobutton', ...
	'Tag','Radiobutton2', ...
	'Value',0);

%% It will be updated : after sensitivity analysis, filter can't be saved
if NextSelectionFlag == 5
    set(h_RadioButton2,'enable','off');
    MonteSetupFlag = 1 ;
end


switch MonteSetupFlag 
case 1
   set(h_RadioButton1,'Value',1);
   if FilterAlgorithmFlag == ALGORITHM_IMM StepNumber = 790 ; else StepNumber = 690 ;end
case 2
   set(h_RadioButton2,'Value',1);
   if FilterAlgorithmFlag == ALGORITHM_IMM StepNumber = 792 ; else StepNumber = 692 ;end
end



help_string=['In this window, you can select one between export tracker and Monte Carlo run'];

set(h_About,'String',help_string, 'enable', 'inactive');
