%%% DynaEst 3.032 10/22/2000
% Copyright (c) 2000 Yaakov Bar-Shalom
%
% MultiSystem , Set parameters(leg time) of Multi Truth System

% Title
h_HeadTitle = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
   'BackgroundColor',FrameBackColor, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[fwsz(1)+fwsz(2)/10 fwsz(2)+fwsz(4)*9/10 fwsz(3)*0.7 10], ...
	'String','Start and finish times of the legs:', ...
	'Style','text', ...
	'Tag','StaticText1');

% From time 
h_From = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*0.3 fwsz(2)+fwsz(4)*(9/10-1/8) fwsz(3)*0.3 15], ...
   'String','From', ...
   'BackgroundColor',FrameBackColor, ...
	'Style','text', ...
	'Tag','StaticText3');
% To 
h_To = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*0.56 fwsz(2)+fwsz(4)*(9/10-1/8) fwsz(3)*0.3 15], ...
   'BackgroundColor',FrameBackColor, ...
   'String','To', ...
	'Style','text', ...
   'Tag','StaticText3');


% First Model
h_Text1 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*(1/10) fwsz(2)+fwsz(4)*(9.5/10-2/7) fwsz(3)*0.3 15], ...
   'BackgroundColor',FrameBackColor, ...
	'String','1st leg:', ...
	'Style','text', ...
   'Tag','StaticText2');

h_Text2 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*(1/10) fwsz(2)+fwsz(4)*(9.5/10-3/7) fwsz(3)*0.3 15], ...
    'String','2nd leg:', ...
   'BackgroundColor',FrameBackColor, ...
   'Style','text', ...
	'Tag','StaticText2');

h_Text3 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*(1/10) fwsz(2)+fwsz(4)*(9.5/10-4/7) fwsz(3)*0.3 15], ...
   'String','3rd leg:', ...   
   'BackgroundColor',FrameBackColor, ...
	'Style','text', ...
   'Tag','StaticText2');

h_Text4 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*(1/10) fwsz(2)+fwsz(4)*(9.5/10-5/7) fwsz(3)*0.3 15], ...
   'BackgroundColor',FrameBackColor, ...
	'String','4th leg:', ...
	'Style','text', ...
   'Tag','StaticText2');

h_Text5 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*(1/10) fwsz(2)+fwsz(4)*(9.5/10-6/7) fwsz(3)*0.3 15], ...
   'String','5th leg:', ...
   'BackgroundColor',FrameBackColor, ...
	'Style','text', ...
   'Tag','StaticText2');


h_Edit1 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*0.38 fwsz(2)+fwsz(4)*(9.5/10-2/7) fwsz(3)*0.15 15], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','EditText2');

h_Edit2 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*0.64 fwsz(2)+fwsz(4)*(9.5/10-2/7) fwsz(3)*0.15 15], ...
	'String','2', ...
	'Style','edit', ...
	'Tag','EditText2');

h_Edit3 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*0.38 fwsz(2)+fwsz(4)*(9.5/10-3/7) fwsz(3)*0.15 15], ...
	'String','3', ...
	'Style','edit', ...
	'Tag','EditText2');

h_Edit4 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*0.64 fwsz(2)+fwsz(4)*(9.5/10-3/7) fwsz(3)*0.15 15], ...
	'String','4', ...
	'Style','edit', ...
	'Tag','EditText2');

h_Edit5 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*0.38 fwsz(2)+fwsz(4)*(9.5/10-4/7) fwsz(3)*0.15 15], ...
	'String','5', ...
	'Style','edit', ...
	'Tag','EditText2');

h_Edit6 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*0.64 fwsz(2)+fwsz(4)*(9.5/10-4/7) fwsz(3)*0.15 15], ...
	'String','6', ...
	'Style','edit', ...
	'Tag','EditText2');

h_Edit7 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*0.38 fwsz(2)+fwsz(4)*(9.5/10-5/7) fwsz(3)*0.15 15], ...
	'String','7', ...
	'Style','edit', ...
	'Tag','EditText2');

h_Edit8 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*0.64 fwsz(2)+fwsz(4)*(9.5/10-5/7) fwsz(3)*0.15 15], ...
	'String','8', ...
	'Style','edit', ...
	'Tag','EditText2');

h_Edit9 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*0.38 fwsz(2)+fwsz(4)*(9.5/10-6/7) fwsz(3)*0.15 15], ...
    'String','9', ...
	'Style','edit', ...
	'Tag','EditText2');

h_Edit10 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*0.64 fwsz(2)+fwsz(4)*(9.5/10-6/7) fwsz(3)*0.15 15], ...
	'String','10', ...
	'Style','edit', ...
	'Tag','EditText2');

set(h_Edit1,'string',num2str(FromTime(1)));
set(h_Edit3,'string',num2str(FromTime(2)));
set(h_Edit5,'string',num2str(FromTime(3)));
set(h_Edit7,'string',num2str(FromTime(4)));
set(h_Edit9,'string',num2str(FromTime(5)));

set(h_Edit2,'string',num2str(ToTime(1)));
set(h_Edit4,'string',num2str(ToTime(2)));
set(h_Edit6,'string',num2str(ToTime(3)));
set(h_Edit8,'string',num2str(ToTime(4)));
set(h_Edit10,'string',num2str(ToTime(5)));

if SimulationFlag == 2 
  set(h_Edit1,'Enable','off');
  set(h_Edit10,'Enable','off');
end

if nmt < 5
   set(h_Text5,'visible','off');
   set(h_Edit9,'visible','off');
   set(h_Edit10,'visible','off');
   if SimulationFlag == 2 
      set(h_Edit8,'Enable','off');
   end
end

if nmt < 4
   set(h_Text4,'visible','off');
   set(h_Edit7,'visible','off');
   set(h_Edit8,'visible','off');
   if SimulationFlag == 2 
      set(h_Edit6,'Enable','off');
   end
end

if nmt < 3
   set(h_Text3,'visible','off');
   set(h_Edit5,'visible','off');
   set(h_Edit6,'visible','off');
   if SimulationFlag == 2 
      set(h_Edit4,'Enable','off');
   end
end

help_string=['In this window, you can specify the starting and finishing times of the motion legs in the true target trajectory.', char(10), char(10), 'For each leg, enter the starting and finishing times.', char(10), char(10), 'Press ''Next >>'' when done to go to the next step. Press ''Close'' to abort the project definition.'];

set(h_About,'String',help_string, 'enable', 'inactive');



