%%% DynaEst 3.032 10/22/2000
% Copyright (c) 2000 Yaakov Bar-Shalom
%
% PopupMenu1, Show Title and Popupmenu on the Common Window

h_HeadTitle = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[70.5 253.5 191.25 18.75], ...
	'String','Set Parameters for each filter in IMM:', ...
	'Style','text', ...
	'Tag','StaticText1');
h_Popupmenu1 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[85.5 189.75 84 62.25], ...
	'Style','popupmenu', ...
	'Tag','PopupMenu1', ...
	'Value',2);

for i = 1:nmf
   str[i] = 'Mode '+ num2str(i);
end

set(h_Popupmenu1,'String',str);
