%%% DynaEst 3.032 10/22/2000
% Copyright (c) 2000 Yaakov Bar-Shalom
%
% SelectTruthFile, Select External Ground Truth File


h_HeadTitle = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
   'HorizontalAlignment','left', ...
   'BackgroundColor',FrameBackColor, ...
	'ListboxTop',0, ...
    'Position',[1.1/12*cwsz(3) 9.3/10*cwsz(4) cwsz(3)/2 10], ...
    'Style','text', ...
   'String','External ground truth File:',...
    	'FontWeight', 'bold', ... 
'Tag','StaticText2');

h_Filename1 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)/6 fwsz(2)+fwsz(4)*1.2/2 fwsz(3)*0.6 fwsz(4)*0.15], ...
	'String',Project_Truth_Filename, ...
	'Style','edit', ...
	'Tag','EditText2');

h_Browse1 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
   'ListboxTop',0, ...
   'Position',[fwsz(1)+fwsz(3)*2/5 fwsz(2)+fwsz(4)/4 fwsz(3)*0.2 fwsz(4)*0.15], ...
   'String','Browse', ...
   'CallBack', [...
      '[filename pathname] = uigetfile(''*.dat'',''Select the External File'');',...
      'if filename ',...
      'Project_Truth_Filename = [pathname,filename];',...
      'set(h_Filename1,''String'',Project_Truth_Filename);',...
   	 'end'],...
	'Tag','Pushbutton7');

