%%% DynaEst 3.032 11/29/2000
% Copyright (c) 2000 Yaakov Bar-Shalom
%
% SelectTrackerFile, Save Tracker(Filter) File

h_HeadTitle = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
   'HorizontalAlignment','left', ...
   'BackgroundColor',FrameBackColor, ...
	'ListboxTop',0, ...
    'Position',[1.1/12*cwsz(3) 9.3/10*cwsz(4) cwsz(3)/2 10], ...
   'Style','text', ...
   'String','Tracking filter export file:',...
 	'FontWeight', 'bold', ... 
	'Tag','StaticText2');

h_Filename1 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)/6 fwsz(2)+fwsz(4)*1.2/2 fwsz(3)*0.6 fwsz(4)*0.15], ...
	'String',Project_Filter_Filename, ...
	'Style','edit', ...
	'Tag','EditText2');

h_Browse1 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
   'ListboxTop',0, ...
   'Position',[fwsz(1)+fwsz(3)*2/5 fwsz(2)+fwsz(4)/4 fwsz(3)*0.2 fwsz(4)*0.15], ...
   'String','Browse', ...
   'CallBack', [...
      '[filename pathname] = uiputfile(''*.mat'',''Filter Export File'');',...
      'if filename ',...
      'Project_Filter_Filename = [pathname,filename];',...
      'set(h_Filename1,''String'',Project_Filter_Filename);',...
   	 'end'],...
	'Tag','Pushbutton7');

help_string=['In this window, you can select the file to which the filter are exported.', char(10), char(10), 'Click on ''Browise'' to select the filter file.', char(10), char(10), 'Press ''Next >>'' when done to go to the next step. Press ''Close'' to abort the export.'];

set(h_About,'String',help_string, 'enable', 'inactive');