%%% DynaEst 3.032 12/20/2000
% Copyright (c) 2000 Yaakov Bar-Shalom
%
% SelectSystemStateFile, select a filename to export system data

set(h_HeadTitle, 'String','System state export file:');

h_Filename1 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)/6 fwsz(2)+fwsz(4)*1.2/2 fwsz(3)*0.6 fwsz(4)*0.15], ...
	'String',Project_State_Filename, ...
	'Style','edit', ...
	'Tag','EditText2');

h_Browse1 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
   'ListboxTop',0, ...
   'Position',[fwsz(1)+fwsz(3)*2/5 fwsz(2)+fwsz(4)/4 fwsz(3)*0.2 fwsz(4)*0.15], ...
   'String','Browse', ...
   'CallBack', [...
      '[filename pathname] = uiputfile(''*.mat'',''System State Export File'');',...
      'if filename ',...
      'Project_State_Filename = [pathname,filename];',...
      'set(h_Filename1,''String'',Project_State_Filename);',...
   	 'end'],...
    'Tag','Pushbutton1');

help_string=['In this window, you can select the file to which the system states are exported.', char(10), char(10), 'Click on ''Browise'' to select the export file.', char(10), char(10), 'Press ''Next >>'' when done to go to the next step. Press ''Close'' to abort the export.'];

set(h_About,'String',help_string, 'enable', 'inactive');