%%% DynaEst 3.032 10/22/2000
% Copyright (c) 2000 Yaakov Bar-Shalom
%
% SensistivityAnalysis: analysis the sensitivity of the filter to mismatch

if ( exist('h_CommonWindow') == 0 ) return; end

if (ishandle(h_CommonWindow) == 0)
   CommonWindow;
end

new_title=1;
if (exist('h_HeadTitle') == 0)

else
  if ishandle(h_HeadTitle)
	new_title=0;
  end
end

if new_title<=0
	set(h_HeadTitle, 'String','Sensitivity analysis:');
else
	h_HeadTitle = uicontrol('Parent',h_CommonWindow, ...
      'Units','points', ...
      'HorizontalAlignment','left', ...
      'ListboxTop',0, ...
      'Position',[1.1/12*cwsz(3) 9.3/10*cwsz(4) cwsz(3)/2 10], ...
  	   'BackgroundColor',FrameBackColor, ...
      'Style','text', ...
      'String','Sensitivity analysis:',... 
	'FontWeight', 'bold', ... 
      'Tag','StaticText2');
end

h_RadioButton1 = uicontrol('Parent',h_CommonWindow, ...
   'Units','points', ...
   'Callback',['set(h_RadioButton1,''Value'',1);',...
      'set(h_RadioButton2,''Value'',0);',...
      'set(h_RadioButton3,''Value'',0);',...
      'set(h_RadioButton4,''Value'',0);',...
      'SensitivityFlag = 1;',...
      'StepNumber = 541;'],...
   'ListboxTop',0, ...
	'BackgroundColor',FrameBackColor, ...
    'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+ fwsz(4)*(7/10) fwsz(3)*8/10 15], ...
    'String','Model mismatch', ...
   'Style','radiobutton', ...
   'Value',0,...
	'Tag','Radiobutton1');

h_RadioButton2 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
   'Callback',['set(h_RadioButton1,''Value'',0);',...
      'set(h_RadioButton2,''Value'',1);',...
      'set(h_RadioButton3,''value'',0);',...
      'set(h_RadioButton4,''Value'',0);',...
      'SensitivityFlag = 2; ',...
      'StepNumber = 542;'],...
   'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+ fwsz(4)*(7/10-1/7) fwsz(3)*8/10 15], ...
    'BackgroundColor',FrameBackColor, ...
	'String','Reduced order filter', ...
   'Style','radiobutton', ...
	'Tag','Radiobutton2', ...
	'Value',0);

h_RadioButton3 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
   'Callback',['set(h_RadioButton1,''Value'',0);',...
      'set(h_RadioButton2,''Value'',0);',...
      'set(h_RadioButton3,''Value'',1);',...
      'set(h_RadioButton4,''Value'',0);',...
      'SensitivityFlag = 3; ',...
      'StepNumber = 543;'],...
   'ListboxTop',0, ...
   'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+ fwsz(4)*(7/10-2/7) fwsz(3)*8/10 15], ...
  	'BackgroundColor',FrameBackColor, ...
   'String','Decoupling', ...
   'enable','off',...
	'Style','radiobutton', ...
	'Tag','Radiobutton3', ...
	'Value',0);
h_RadioButton4 = uicontrol('Parent',h_CommonWindow, ...
   'Units','points', ...
   'Callback',['set(h_RadioButton1,''Value'',0);',...
      'set(h_RadioButton2,''Value'',0);',...
      'set(h_RadioButton3,''Value'',0);',...
      'set(h_RadioButton4,''Value'',1);',...
      'SensitivityFlag = 4; ',...
      'StepNumber = 544;'],...
  	'BackgroundColor',FrameBackColor, ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+ fwsz(4)*(7/10-3/7) fwsz(3)*8/10 15], ...
	'String','Fixed filter gain', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton4');

if SensitivityFlag == -1
   SensitivityFlag = 1;
end

if SensitivityFlag == 1
   set(h_RadioButton1,'value',1);
   StepNumber = 541;
elseif SensitivityFlag == 2
   set(h_RadioButton2,'value',1);
   StepNumber = 542;
elseif SensitivityFlag == 3
   set(h_RadioButton3,'value',1);
   StepNumber = 543;
elseif SensitivityFlag == 4
   set(h_RadioButton4,'value',1);
   StepNumber = 544;
end

help_string=['In this window, you can select an option for filter sensitivity analysis.', char(10), char(10), 'DynaEst has the capability to analyze the effects of the following: model mismatch, reduced order filtering, state decopling, and fixed filter gain.', char(10), char(10), 'Press ''Next >>'' after selecting an analysis option to go to the next step. Press ''Close'' to abort the analysis.'];

set(h_About,'String',help_string, 'enable', 'inactive');



   
