%%% DynaEst 3.032 10/22/2000
% Copyright (c) 2000 Yaakov Bar-Shalom
%
% SizeOfReducedModel, show and input the size of Reduced Order model 

set(h_HeadTitle, 'String','Reduced order sensitivity analysis:');

h_Text1 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+fwsz(4)*(8.2/10-2/6.5) fwsz(3)*0.6 15], ...
    'String','Dimension of reduced order filter state nr =', ...
	'Style','text', ...
	'Tag','StaticText1');

h_Edit1 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*0.72 fwsz(2)+fwsz(4)*(8.2/10-2/6.5) fwsz(3)*0.12 15], ...
    'String','3', ...
	'Style','edit', ...
	'Tag','EditText1');

if exist('nr','var') == 0
   nr = nx -1;
end

if nr >= nx
   nr = nx -1;
end

set(h_Edit1,'string',num2str(nr));

% About information

help_string=['In this window, you can set the dimension of the reduced order filter state.', char(10), char(10), 'Make sure that the dimension is less than or equal to the dimension of the true state.', char(10), char(10), 'Press ''Next >>'' when done to go to the next step. Press ''Close'' to abort the analysis.'];

set(h_About,'String',help_string, 'enable', 'inactive');