%%% DynaEst 3.032 10/22/2000
% Copyright (c) 2000 Yaakov Bar-Shalom
%
% sojourntimeInput.m show and input the sojourn time for each mode,
% and input upperlimit and lowerlimit of transition probability

if exist('h_HeadTitle1') 
  if ishandle(h_HeadTitle1)
	delete(h_HeadTitle1);
  end
end

new_title=1;
if exist('h_HeadTitle') 
  if ishandle(h_HeadTitle)
	new_title=0;
  end
end

if new_title ==0
	set(h_HeadTitle, 'String','IMM estimator parameters:');
else
	h_HeadTitle = uicontrol('Parent',h_CommonWindow, ...
      'Units','points', ...
      'HorizontalAlignment','left', ...
      'ListboxTop',0, ...
      'Position',[1.1/12*cwsz(3) 9.3/10*cwsz(4) cwsz(3)/2 10], ...
      'BackgroundColor',FrameBackColor, ...
      'Style','text', ...
      'String','IMM estimator parameters:',... 
	'FontWeight', 'bold', ... 
      'Tag','StaticText2');
end


h_HeadTitle1 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
   'BackgroundColor',FrameBackColor,...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+fwsz(4)*8/10 fwsz(3)*0.5 15], ...
	'String','Model 1', ...
	'Style','text', ...
	'Tag','StaticText4');

h_Text1 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+fwsz(4)*(8/10-8/40) fwsz(3)*0.5 15], ...
   'BackgroundColor',FrameBackColor,...
	'String','Sojourn time:', ...
	'Style','text', ...
	'Tag','StaticText1');
h_Edit1 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)*0.5 fwsz(2)+fwsz(4)*(8/10-8/40) fwsz(3)*0.1 15], ...
	'Style','edit', ...
   'Tag','EditText2');

% lower limit
h_Text2 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
   'HorizontalAlignment','left', ...
   'BackgroundColor',FrameBackColor,...
	'ListboxTop',0, ...
    'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+fwsz(4)*(8/10-16/40) fwsz(3)*0.5 15], ...
	'String','Diagonal lower limit:', ...
	'Style','text', ...
   'Tag','StaticText2');
h_Edit2 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
   'ListboxTop',0, ...
  	'HorizontalAlignment','left', ...
    'Position',[fwsz(1)+fwsz(3)*0.5 fwsz(2)+fwsz(4)*(8/10-16/40) fwsz(3)*0.1 15], ...
   'Style','edit', ...
   'Tag','EditText3');

h_Text3 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'HorizontalAlignment','left', ...
   'ListboxTop',0, ...
   'BackgroundColor',FrameBackColor,...
   'Position',[fwsz(1)+fwsz(3)/10 fwsz(2)+fwsz(4)*(8/10-24/40) fwsz(3)*0.5 15], ...
   'String','Diagonal upper limit: ', ...
	'Style','text', ...
   'Tag','StaticText3');

h_Edit3 = uicontrol('Parent',h_CommonWindow, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'HorizontalAlignment','left', ...
    'Position',[fwsz(1)+fwsz(3)*0.5 fwsz(2)+fwsz(4)*(8/10-24/40) fwsz(3)*0.1 15], ...
   'Style','edit', ...
	'Tag','EditText4');

set(h_Edit1,'string',num2str(SojournTime(mode)));
set(h_Edit2,'string',num2str(LowerLimit(mode)));
set(h_Edit3,'string',num2str(UpperLimit(mode)));


help_string=['In this window, you can set the sojourn time of the IMM filter models.', char(10), char(10), 'Enter the sojourn time in the particular mode and DynaEst will adaptively modify the corresponding diagonal term in the mode transition probability matrix based on the revisit interval and the sojourm time. Also specify the minimum and the maximum values for the corresponding diagonal terms.', char(10), char(10), 'Press ''Next >>'' when done to go to the next step. Press ''Close'' to abort the project definition.'];

set(h_About,'String',help_string, 'enable', 'inactive');
