%%% DynaEst 3.032 10/22/2000
% Copyright (c) 2000 Yaakov Bar-Shalom
%
% Start , This is the first Window for a Simulation Process

load Start

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'Name','Welcome to DynaEst System!', ...
	'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
	'Position',[185 110 579 443], ...
	'Tag','Fig1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','close(''Welcome to DynaEst System!''); GroundTruth;', ...
	'ListboxTop',0, ...
	'Position',[333 270 69 22.5], ...
	'String','Start >>', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[333 225 69 22.5], ...
	'String','<< Prev', ...
	'Tag','Pushbutton2');
% $$$ h1 = uicontrol('Parent',h0, ...
% $$$ 	'Units','points', ...
% $$$ 	'ListboxTop',0, ...
% $$$ 	'Position',[333 180 69 22.5], ...
% $$$ 	'String','Reset', ...
% $$$ 	'Tag','Pushbutton3');
% $$$ h1 = uicontrol('Parent',h0, ...
% $$$ 	'Units','points', ...
% $$$ 	'ListboxTop',0, ...
% $$$ 	'Position',[333 135.5 69 22.5], ...
% $$$ 	'String','Auto Play', ...
% $$$ 	'Tag','Pushbutton4');
% $$$ h1 = uicontrol('Parent',h0, ...
% $$$ 	'Units','points', ...
% $$$ 	'ListboxTop',0, ...
% $$$ 	'Position',[333 65 69 22.5], ...
% $$$ 	'String','Info', ...
% $$$ 	'Tag','Pushbutton5');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback',' Close(''Welcome to DynaEst System!''); End;', ...
	'ListboxTop',0, ...
	'Position',[333 20 69 22.5], ...
	'String','Close', ...
	'Tag','Pushbutton6');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[30 44.25 270 114], ...
	'String','This is About ...', ...
	'Style','edit', ...
	'Tag','EditInformationText');
