---------------------------------------
-- Generated by SIMECT
-- Generated on: 06-May-2011 12:32:21
---------------------------------------

LIBRARY IEEE;
USE IEEE.electrical_systems.all;
use IEEE.math_real.all;
USE work.all;

ENTITY test_v_uni_v_uni IS

  PORT    (TERMINAL Vin,Vout: ELECTRICAL);

END ENTITY test_v_uni_v_uni;

ARCHITECTURE behavioral OF test_v_uni_v_uni IS

  CONSTANT Out_1_Num_TF_dir1_1 : REAL_VECTOR := (8.080523521257e-01, 1.905564763746e-11, 8.808222705263e-25, 0.0);
  CONSTANT Out_1_Den_TF_dir1_1 : REAL_VECTOR := (1.000000000000e+00, 2.773341596048e-11, 1.281666983644e-24, 0.0);
  CONSTANT Out_1_Num_TF_inv1_1 : REAL_VECTOR := (1.205085427387e-18, -2.038412441016e-11, -9.428140963994e-25, 0.0);
  CONSTANT Out_1_Den_TF_inv1_1 : REAL_VECTOR := (1.000000000000e+00, 2.773341596048e-11, 1.281666983645e-24, 0.0);
  CONSTANT Out_1_Num_Zin1_1 : REAL_VECTOR := (1.000000000000e+00, 3.065889192376e-11, 9.754989298025e-26, 0.0);
  CONSTANT Out_1_Den_Zin1_1 : REAL_VECTOR := (1.224613729992e-07, 1.345960955964e-14, 5.791872311970e-25, 0.0);
  CONSTANT Out_1_Num_Zout1_1 : REAL_VECTOR := (1.000000000000e+00, 3.078829908835e-13, 1.649751531738e-26, 0.0);
  CONSTANT Out_1_Den_Zout1_1 : REAL_VECTOR := (2.053538290091e-03, 5.699844142106e-14, 3.927981974514e-27, 0.0);
  CONSTANT Out_1_OffIn11 : REAL := 1.500000e+00;
  CONSTANT Out_1_OffIn12 : REAL := 0.000000e+00;
  CONSTANT Out_1_OffOut11 : REAL := 5.432017e-01;
  CONSTANT Out_1_OffOut12 : REAL := 0.000000e+00;
  QUANTITY Vin_1 ACROSS Iin_1 THROUGH Vin TO ground; 
  QUANTITY Vout_1 ACROSS Iout_1 THROUGH Vout TO ground; 
  QUANTITY deltaVin: voltage;
  QUANTITY deltaIout_1: current;

BEGIN

  deltaVin == Vin_1 - Out_1_OffIn11;
  deltaIout_1 == Iout_1 - Out_1_OffOut12;
  Vout_1 == deltaVin'LTF(Out_1_Num_TF_dir1_1,Out_1_Den_TF_dir1_1)+ deltaIout_1'LTF(Out_1_Num_Zout1_1,Out_1_Den_Zout1_1)+ Out_1_OffOut11;
  Iin_1 == deltaVin'LTF(Out_1_Den_Zin1_1,Out_1_Num_Zin1_1)+ deltaIout_1'LTF(Out_1_Num_TF_inv1_1,Out_1_Den_TF_inv1_1)+ Out_1_OffIn12;

END ARCHITECTURE behavioral;

